<a href="https://colab.research.google.com/github/thanachai-npr/CE888/blob/main/lab4/my_recommender.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn.svm import SVC

np.set_printoptions(precision=3)

In [2]:
jokes_df = pd.read_csv("https://raw.githubusercontent.com/albanda/CE888/master/lab4-recommender/jester-data-1.csv",  header = None)
df = jokes_df.replace(99, np.NaN)
df.drop([0], axis=1, inplace = True)
print(df)


        1     2     3     4     5     6    ...   95    96    97    98    99    100
0     -7.82  8.79 -9.66 -8.16 -7.52 -8.50  ...   NaN   NaN -5.63   NaN   NaN   NaN
1      4.08 -0.29  6.36  4.37 -2.38 -9.66  ... -0.19 -2.14  3.06  0.34 -4.32  1.07
2       NaN   NaN   NaN   NaN  9.03  9.27  ...   NaN   NaN   NaN   NaN   NaN   NaN
3       NaN  8.35   NaN   NaN  1.80  8.16  ...   NaN   NaN   NaN   NaN   NaN   NaN
4      8.50  4.61 -4.17 -5.39  1.36  1.60  ...  5.73  1.55  3.11  6.55  1.80  1.60
...     ...   ...   ...   ...   ...   ...  ...   ...   ...   ...   ...   ...   ...
24978  0.44  7.43  9.08  2.33  3.20  6.75  ...  8.45  9.03  6.55  8.69  8.79  7.43
24979  9.13 -8.16  8.59  9.08  0.87 -8.93  ...  9.22 -8.20 -7.23 -8.59  9.13  8.45
24980   NaN   NaN   NaN   NaN -7.77   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN
24981   NaN   NaN   NaN   NaN -9.71   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN
24982  2.43  2.67 -3.98  4.27 -2.28  7.33  ...   NaN   NaN   NaN   NaN   NaN   NaN

[24

In [3]:
arr = df.values
print(arr)

[[-7.82  8.79 -9.66 ...   nan   nan   nan]
 [ 4.08 -0.29  6.36 ...  0.34 -4.32  1.07]
 [  nan   nan   nan ...   nan   nan   nan]
 ...
 [  nan   nan   nan ...   nan   nan   nan]
 [  nan   nan   nan ...   nan   nan   nan]
 [ 2.43  2.67 -3.98 ...   nan   nan   nan]]


In [4]:
def replace(orig, percentage=0.1):
  """
  Replaces 'percentage'% of the original values in 'orig' with 99's
  :param orig: original data array
  :param percentage: percentage of values to replace (0<percentage<1)
  """
  new_data = orig.copy()
  rated = np.where(~np.isnan(orig))
  n_rated = len(rated[0])
  idx = np.random.choice(n_rated, size=int(percentage*n_rated), replace=False)
  for i in idx:
    assert new_data[rated[0][i], rated[1][i]] != np.nan
  new_data[rated[0][idx], rated[1][idx]] = 99
  return new_data, (rated[0][idx], rated[1][idx])

In [5]:
new_arr, idx = replace(arr, 0.1)

In [6]:
print(new_arr)

[[-7.82  8.79 -9.66 ...   nan   nan   nan]
 [ 4.08 -0.29  6.36 ...  0.34 -4.32  1.07]
 [  nan   nan   nan ...   nan   nan   nan]
 ...
 [  nan   nan   nan ...   nan   nan   nan]
 [  nan   nan   nan ...   nan   nan   nan]
 [ 2.43  2.67 -3.98 ...   nan   nan   nan]]


In [7]:
print(arr)

[[-7.82  8.79 -9.66 ...   nan   nan   nan]
 [ 4.08 -0.29  6.36 ...  0.34 -4.32  1.07]
 [  nan   nan   nan ...   nan   nan   nan]
 ...
 [  nan   nan   nan ...   nan   nan   nan]
 [  nan   nan   nan ...   nan   nan   nan]
 [ 2.43  2.67 -3.98 ...   nan   nan   nan]]


In [8]:
n_latent_factors = 2

user_ratings = new_arr
# Initialise as random values
latent_user_preferences = np.random.random((user_ratings.shape[0], n_latent_factors))
latent_item_features = np.random.random((user_ratings.shape[1], n_latent_factors))

In [9]:
latent_item_features

array([[0.792, 0.954],
       [0.441, 0.006],
       [0.982, 0.607],
       [0.226, 0.706],
       [0.834, 0.8  ],
       [0.738, 0.858],
       [0.558, 0.82 ],
       [0.609, 0.67 ],
       [0.77 , 0.658],
       [0.516, 0.842],
       [0.869, 0.164],
       [0.823, 0.492],
       [0.435, 0.97 ],
       [0.289, 0.346],
       [0.917, 0.776],
       [0.96 , 0.551],
       [0.263, 0.13 ],
       [0.229, 0.818],
       [0.248, 0.724],
       [0.779, 0.475],
       [0.084, 0.256],
       [0.89 , 0.432],
       [0.211, 0.126],
       [0.394, 0.723],
       [0.438, 0.697],
       [0.167, 0.447],
       [0.31 , 0.56 ],
       [0.209, 0.358],
       [0.655, 0.437],
       [0.084, 0.861],
       [0.25 , 0.22 ],
       [0.423, 0.777],
       [0.871, 0.724],
       [0.244, 0.721],
       [0.636, 0.269],
       [0.773, 0.202],
       [0.672, 0.405],
       [0.546, 0.798],
       [0.283, 0.181],
       [0.605, 0.936],
       [0.784, 0.592],
       [0.396, 0.807],
       [0.918, 0.077],
       [0.2

In [10]:
latent_user_preferences

array([[0.693, 0.604],
       [0.536, 0.132],
       [0.179, 0.48 ],
       ...,
       [0.759, 0.96 ],
       [0.04 , 0.838],
       [0.346, 0.754]])

In [11]:
def predict_rating(user_id, item_id):
    """ Predict a rating given a user_id and an item_id.
    """
    user_preference = latent_user_preferences[user_id]
    item_preference = latent_item_features[item_id]
    return user_preference.dot(item_preference)


def train(user_id, item_id, rating, alpha=0.0001):
    #print(item_id)
    predicted_rating = predict_rating(user_id, item_id)
    err =  predicted_rating - rating
    #print(err)
    user_pref_values = latent_user_preferences[user_id]
    latent_user_preferences[user_id] -= alpha * err * latent_item_features[item_id]
    latent_item_features[item_id] -= alpha * err * user_pref_values
    return err

def sgd(iterations):
    """ 
    Iterate over all users and all items and train for 
    a certain number of iterations
    """
    
    for iteration in range(iterations):
        error = []
        for user_id in range(latent_user_preferences.shape[0]):
            for item_id in range(latent_item_features.shape[0]):
              rating = user_ratings[user_id, item_id]
              if not np.isnan(rating) and rating != 99:
                err = train(user_id, item_id, rating)
                error.append(err)
    mse = (np.array(error) ** 2).mean()          
    print(mse)

In [13]:
sgd(5)

22.747271764806445


In [72]:
df.iloc[18473, 0]

nan

In [105]:
item_features_df = pd.read_excel('movies_latent_factors.xlsx', sheet_name='Items',index_col='Movie ID')
user_ratings_df = pd.read_excel('movies_latent_factors.xlsx', sheet_name='Users',index_col='User')
item_features_df = item_features_df.drop('Title', axis=1)

In [111]:
item_features_df = item_features_df.values
print(item_features_df)


[[-1.522 -1.039  2.027 ...  0.404  1.13  -0.249]
 [-0.342 -0.297 -0.386 ... -0.564  0.507  1.275]
 [-2.241 -0.439 -2.275 ... -0.33  -2.209 -0.419]
 ...
 [ 0.812 -0.893  0.669 ...  0.642 -1.356  0.068]
 [ 1.161 -0.716  0.713 ...  0.291 -1.217 -0.288]
 [ 1.734  0.265 -0.003 ...  0.334 -0.223 -0.023]]


In [112]:
user_ratings_df = user_ratings_df.values
print(user_ratings_df)

[[-2.040e-01  1.611e-01 -9.045e-02  1.385e-01 -1.629e-01  1.639e-01
   5.150e-02 -8.858e-02  1.268e-01  6.597e-02  8.501e-02  3.554e-01
   7.108e-03 -1.187e-01 -3.913e-02]
 [-1.897e-01 -1.790e-01 -9.149e-02 -8.228e-04 -3.265e-02  1.772e-01
  -9.812e-02 -6.828e-02 -1.157e-02  1.209e-01 -9.931e-03 -4.861e-02
   4.592e-02  1.137e-01  1.799e-01]
 [-1.153e-01 -9.089e-02 -5.313e-02  1.847e-02 -6.808e-02 -4.828e-03
   1.130e-01  1.021e-01  3.476e-02  6.926e-04 -7.371e-02 -1.946e-02
   1.084e-01  5.447e-02 -1.096e-01]
 [-2.275e-01 -2.725e-01 -1.723e-02  5.432e-02  2.148e-01 -7.264e-02
  -3.312e-02 -8.651e-02 -1.315e-01  1.804e-01  9.589e-02 -8.240e-02
   3.677e-02 -1.654e-01  5.069e-02]
 [-1.462e-02 -1.022e-01 -1.079e-01  1.558e-01 -1.234e-01 -1.182e-01
  -1.355e-02 -5.062e-02  5.870e-02 -1.596e-01 -1.424e-01 -1.328e-01
  -3.990e-02  1.291e-01  1.027e-01]
 [-2.030e-02 -3.192e-02 -3.696e-02  3.369e-02  1.745e-04 -3.178e-03
   5.447e-02  4.542e-02 -5.331e-02  3.437e-03 -4.175e-02  5.973e-02
  -2

In [113]:
##Q7
rating = user_ratings_df[15].dot(item_features_df[46])
print(rating)

-0.09541436887627988


In [114]:
##Q8
rating = user_ratings_df[22].dot(item_features_df[54])
print(rating)

0.3682088030139018


In [125]:
##Q9
rating = []
for i in range(len(item_features_df)):
  rating.append(user_ratings_df[14].dot(item_features_df[i]))

TypeError: ignored

In [126]:
##Q10

AttributeError: ignored

Factor1  ...                                    Factor15
0     (-1.5218476932977845, 0.980999454175521)  ...  (-0.24880587477821164, 1.0018550953939052)
1    (-0.3421850499080402, 0.7461582276240474)  ...    (1.2749928648278452, 1.2685946181642158)
2     (-2.240887934508497, 0.7662978800133377)  ...   (-0.4190918295482105, 1.1398335840142721)
3    (-0.6345314311929691, 0.9362455401205368)  ...    (-0.681191273804317, 0.9075830056839858)
4      (0.5173475586768793, 0.531051879378947)  ...     (-2.2925659870564994, 0.82088256260412)
5    (-0.6450193025539236, 1.1661846984559832)  ...    (1.0366559262647952, 1.1955417010200953)
6   (-0.6955385943024123, 0.31116174437582067)  ...    (0.2374580511571721, 1.1337333416767001)
7    (-0.6156234603330047, 0.7098930486400359)  ...    (0.4320055828595556, 0.7454224898594631)
8   (-1.4437300947749632, 0.30956442713165766)  ...     (0.5052651984719501, 0.903977115012866)
9    (-1.2417242059129892, 0.3331772664274388)  ...   (-0.1976860575680101, 0.8435573045810543)
10  (-1.3648519459394857, 0.27999216957016976)  ...  (-0.17556519562223152, 1.0223482641289363)
11     (-1.107665975252439, 0.611944930440775)  ...   (0.11802446106583232, 0.5971226814126515)
12   (-0.7154995971213342, 0.4361236522696614)  ...   (-0.4414625731855268, 0.6581425066244215)
13      (1.658680671871899, 0.761185345029056)  ...   (-0.1624116323431699, 0.6303038882478852)
14   (-2.2473949986146313, 0.7057762797364576)  ...   (-0.27628012281468367, 1.073386603045926)

[15 rows x 15 columns]